# Uncomment for production
# baseURL = 'https://detektywdomanski.pl/' Uncomment for production
#

languageCode = 'pl'
title = 'Detektyw Domański'
uglyURLs = false

# Delete for production
baseURL = "/"
relativeURLs = true
#

disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

trailingSlash = "always" 

