# Uncomment for production
# baseURL = 'https://detektywdomanski.pl/' Uncomment for production
#

languageCode = 'pl'
title = 'Detektyw Domański'
uglyURLs = false

# Delete for production
baseURL = "/"
relativeURLs = true
#

[menu]
  [[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 1

[taxonomies]
  tag = "tags"
  category = "categories"

trailingSlash = "always" 

